#ifndef MERGE_SORT_H
#define MERGE_SORT_H

#include <cstddef>
#include <vector>

// Do not edit this file. The autograder uses these declarations to test
// merge() and mergeSortRange() separately.

// Merge two adjacent sorted ranges through one reusable scratch vector.
//
// Precondition:
//   ar[lo .. md] and ar[md + 1 .. hi] are each sorted in ascending order;
//   lo <= md < hi; scratch.size() >= ar.size().
// Postcondition:
//   ar[lo .. hi] contains the same keys, sorted in ascending order;
//   positions of ar outside lo .. hi are unchanged;
//   scratch[lo .. hi] holds that same merged sequence.
//
// The last clause is part of the contract and is checked: the merge must
// actually be performed through scratch. Merging through temporaries of your
// own and leaving scratch untouched does not satisfy it, even if ar comes out
// sorted.
//
// So that this is a stated requirement rather than a hidden trap:
//
//   * scratch IS the workspace. merge() and mergeSortRange() must not create
//     another one -- no local vector, array or buffer of your own, and nothing
//     allocated with new or malloc. Only mergeSort() allocates, once.
//   * Write the merge yourself. std::sort, std::stable_sort, std::merge,
//     std::inplace_merge and qsort are not permitted here; sorting the range by
//     some other means and copying the result into scratch reproduces the
//     values without doing the exercise.
//   * mergeSortRange() must recurse, as the handout describes: base case,
//     midpoint, two recursive calls, then merge().
//
// All three are checked.
void merge(std::vector<int> &ar, std::vector<int> &scratch, std::size_t lo,
           std::size_t md, std::size_t hi);

// Sort ar[lo .. hi] recursively, reusing scratch as workspace.
// Precondition: scratch.size() >= ar.size().
void mergeSortRange(std::vector<int> &ar, std::vector<int> &scratch,
                    std::size_t lo, std::size_t hi);

// Entry point used by main.cpp. Allocates scratch once and calls
// mergeSortRange().
void mergeSort(std::vector<int> &ar, std::size_t lo, std::size_t hi);

#endif  // MERGE_SORT_H
